package:
  name: distribexp
  version: "v0.1"

source:
  git_rev: "v0.1"
  git_url: "https://github.com/skippyelvis/distribexp.git"

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - distribexp

about:
  home: "https://github.com/skippyelvis/distribexp"
  license: BSD
  license_family: BSD
  summary: Ditributed experiment tools